src/drivers/base.py, tests/test_count.py, tests/test_select.py
When you want to do COUNT(DISTINCT(column))
=> Add count(expr)

src/drivers/base.py
**ClickHouseDialect.get_schema_names** was not implemented: its role is just to list the databases.
The implementation already exists in cloudfare sqlalchemy-clickhouse driver so it does make sense to also support it here.
=> Support for get_schema_names in Dialect

clickhouse_sqlalchemy/drivers/http/connector.py, clickhouse_sqlalchemy/drivers/native/connector.py
=> refactor Cursor.__iter__ to conform with PEP 479

clickhouse_sqlalchemy/drivers/native/connector.py, tests/drivers/native/test_cursor.py
Following my bug report #39 , here's a simple check on context during execute preparation.
It does fix the raw connection execution and make no changes when a context is set (vast majority of use cases) however it implies that no execution options can be passed when in raw mode.
=> fix raw connection execute

.gitignore, clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/types.py, tests/test_reflection.py
Currently when using
```
e = sa.create_engine(...)
md = sa.MetaData(bind=e)
md.reflect()
```
warnings are logged due to unrecognized types. This occurs due to `Enum8`/`Enum16` being improperly instantiated, without their options.
And in fact, the `DESCRIBE TABLE` calls returns the following: 
```
DESCRIBE TABLE t1
┌─name────────────────┬─type─────────────────────────────────────────────────────────────────────┬─default_type─┬─default_expression─┐
│ id                  │ UInt64                                                                   │              │                    │
│ t_type              │ Enum8('left' = 1, 'right' = 2)                                           │              │                    │
└─────────────────────┴──────────────────────────────────────────────────────── …
```
=> Column type to return Enum instead of NullType

CHANGELOG.md, clickhouse_sqlalchemy/drivers/base.py, tests/orm/test_select.py
The `full` parameter was not checked in `visit_join`, resulting in `LEFT OUTER JOIN` syntax regardless of its value.
Matches standard syntax:
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/base.py#L1367
=> fixed support for `full` parameter in joins

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/engines.py, tests/drivers/http/test_transport.py, tests/drivers/test_clickhouse_dialect.py, tests/orm/test_select.py, tests/test_engines.py
* _get_server_info implemented
* declarative engines parameters
=> Ability to use custom partition key and primary keys differs from sorting keys for *MergeTree 

clickhouse_sqlalchemy/drivers/http/utils.py, tests/drivers/http/test_utils.py
There are such cases when clickhouse table can contain wrong symbols that couldn't be found in the utf-8 table. This pull request should handle UnicodeDecodeError.
=> Fix UnicodeDecodeError

.travis.yml, clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/types.py, setup.py, tests/test_types.py, tests/util.py
This PR adds IPv4 and IPv6 support in sqlalchemy, following the work done in clickhouse-driver.
Note that as no release of clickhouse-driver with IP support is available in pip yet, travis will fail for now. Nonetheless all tests are passing on my computer on python 3.6 and 2.7 (with clickhouse 19.3.3+).
I have also added the require_server_version decorator to be used in tests so IP related tests run only on 19.3.3+
Finally as clickhouse only support basic comparators for IP, I have added the *in* and *not in* operators to generate proper queries, see tests for examples.
=> Add native IPv4 and IPv6 types support

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/orm/query.py, clickhouse_sqlalchemy/sql/schema.py, clickhouse_sqlalchemy/sql/selectable.py, tests/orm/test_select.py, tests/sql/test_schema.py, tests/sql/test_selectable.py
OK, here is a join support for standard sqla-core ([issue](https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/35)) and some kind of joins-api refactor.
Example is here: `tests.sql.test_schema.SchemaTestCase#test_reflect`.
The magic is here: `clickhouse_sqlalchemy.drivers.base.ClickHouseDialect#reflecttable`.
I replace table bounded with metadata by the table with another class.
The place that can make you sad is `clickhouse_sqlalchemy.orm.query.Query#join`. But I hope it is not: can't invent another way to make this possible: there are a lot of work inside of `sqlalchemy.orm.query.Query#join` method which should be done, but in the and another class must be used.
=> joins support

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/types.py, tests/test_reflection.py
Context: it is a poorly documented type modifier with minimal-to-none client-side effect
=> Support LowCardinality type modifier

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/drivers/http/base.py, clickhouse_sqlalchemy/drivers/http/connector.py, clickhouse_sqlalchemy/drivers/http/escaper.py, clickhouse_sqlalchemy/drivers/http/transport.py, clickhouse_sqlalchemy/drivers/native/base.py, clickhouse_sqlalchemy/drivers/native/connector.py, tests/config.py, tests/drivers/http/test_escaping.py, tests/drivers/http/test_select.py, tests/drivers/http/test_stream.py, tests/drivers/http/test_transport.py, tests/drivers/http/test_utils.py, tests/drivers/native/test_select.py, tests/drivers/test_clickhouse_dialect.py, tests/functions/test_count.py, tests/orm/test_select.py, tests/session.py, tests/sql/test_limit.py, tests/sql/test_schema.py, tests/test_compiler.py, tests/test_ddl.py, tests/test_reflection.py, tests/test_types.py, tests/testcase.py, tests/util.py
clickhouse-over-HTTP is **not** obsolete.
This is a preliminary pull request; merging various improvements and fixes to upstream.
=> HTTP-session tests, assorted fixes

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/orm/query.py, clickhouse_sqlalchemy/sql/selectable.py, tests/orm/test_select.py, tests/sql/test_selectable.py
FINAL modifier added
[https://clickhouse.tech/docs/ru/query_language/select/#select-from-final](url)
=> final clause

clickhouse_sqlalchemy/engines.py, tests/test_engines.py
ReplacingMergeTree param version_col moved after *args, because named arguments should go after positional.
SummingMergeTree have same problem, but I don't know, how it shold work, so I didn't touch it.
=> named arguments should go after positional

README.rst, clickhouse_sqlalchemy/drivers/base.py, tests/test_ddl.py
Continuing the discussion [from here](https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/88#issuecomment-596418440), this implements the required changes to add support for the dialect-specific `CODEC(...)` column option. Thank you for the hints regarding the implementation, they proved helpful in getting this started! 
I got a little bit confused by your original message mentioning `visit_column` and realizing that this method only generates the column name, however looking around in the MSSQL implementation revealed that overriding `get_column_specification` appears the be the way to go. I never thought that MSSQL would prove to be helpful for anything in my life, but I stand corrected.
In the edited comment you changed it to `visit_create_column`, which I tested and can confirm …
=> Add support for `CODEC` column option

clickhouse_sqlalchemy/types.py, clickhouse_sqlalchemy/util/comparators.py, tests/test_types.py
This improves the IP types support in 2 aspects:
- add support for literal binds (was missing)
- extensive implementation of IN and NOT IN comparators (compared to the primitive one currently in place)
The Comparator implementation is here to overcome the basic Clickhouse implementation for IP types by generating complex AND & OR combinations, but this has the advantage of covering a lot - if not all - cases (see tests).
As the IPv4 and IPv6 comparators have exactly the same behavior, I've extracted a common base implementation to keep it clean.
All the required tests are added.
=> Improve IP types

clickhouse_sqlalchemy/drivers/base.py
This PR makes the following code execute without errors:
```python
import sqlalchemy
import clickhouse_sqlalchemy.engines
metadata = sqlalchemy.MetaData()
notes = sqlalchemy.Table(
"notes",
metadata,
sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
sqlalchemy.Column("text", sqlalchemy.String(length=100)),
clickhouse_sqlalchemy.engines.Memory(),
)
engine = sqlalchemy.create_engine("clickhouse://default:@0.0.0.0:8123")
metadata.create_all(engine)
metadata.drop_all(engine)
```
Related to #22
**Can you please make a new PyPI release after merging this.**
=> Fix if_exists and on_cluster AttributeError-s

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/engines/mergetree.py, clickhouse_sqlalchemy/sql/ddl.py, tests/engines/test_compilation.py, tests/engines/test_reflection.py
Implementation for TTL
```
CREATE TABLE example_table
(
d DateTime,
a Int
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(d)
ORDER BY d
TTL d + INTERVAL 1 MONTH [DELETE],
d + INTERVAL 1 WEEK TO VOLUME 'aaa',
d + INTERVAL 2 WEEK TO DISK 'bbb';
```
Usage
from clickhouse_sqlalchemy.sql.ddl import ttl_delete, ttl_to_disk, ttl_to_volume
class TestTable(self.base):
date = Column(types.Date, primary_key=True)
x = Column(types.Int32)
__table_args__ = (
engines.MergeTree(
ttl=[
ttl_delete(date + func.toIntervalDay(1)),
ttl_to_disk(date + func.toIntervalDay(1), 'hdd'),
ttl_to_volume(date + func.toIntervalDay(1), 'slow'),
],
),
)
=> TTL param for engine

clickhouse_sqlalchemy/drivers/http/transport.py
Use `requests.Session.post()` instead of `requests.post()` to reuse HTTP connections between queries.
=> Keep HTTP connection open between queries

clickhouse_sqlalchemy/drivers/base.py
The server version handling code is assuming all version components are numeric, which isn't the case when the fourth component is a build tag (such as `12-stable-98abc83`). This causes an exception when connecting to servers.
This PR keeps version components as a string when they can't be parsed as an integer (although I feel the proper course of action here would be returning the unparsed version in the tuple, and then use `distutils.version.LooseVersion` for comparisons in `ClickHouseDialect.initialize()`.
=> Fix server version parsing (non-numeric build)

README.rst, clickhouse_sqlalchemy/__init__.py, clickhouse_sqlalchemy/drivers/http/transport.py
By allowing the user to pass a `requests.Session` object (or subclass instance), it becomes possible to manipulate the underlying HTTP connection in custom ways without modifying the driver.
Example use cases:
* Complex mocking of database responses for testing;
* Transparently cache (some) responses;
* Perform complex authentication;
* ...
The version is bumped to 0.1.6 because this introduces a change in the API and allows users to specify `>=0.1.6` in their requirements files.
=> Allow custom requests.Session for HTTP

clickhouse_sqlalchemy/__init__.py, clickhouse_sqlalchemy/drivers/http/transport.py, clickhouse_sqlalchemy/drivers/http/utils.py, tests/drivers/http/test_utils.py
By default strings are being decoded into unicode in a way that makes it impossible to encode them back into what's actually in the database (`errors='replace'`). This causes "data loss" when tables have columns that are supposed to store raw bytes.
An option `unicode_errors` is added that allows changing this behavior (e.g. by passing `unicode_errors=surrogateescape`). The default behavior is kept unchanged for compatibility and the driver minor version is bumped.
=> Don't lose information on unicode conversion

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/engines/__init__.py, clickhouse_sqlalchemy/engines/misc.py, tests/drivers/test_clickhouse_dialect.py
This PR fixes three things that came up in testing against Superset. With 
these changes it is possible in Superset to create datasets on views 
as well as on tables in schemas other than the default schema.  
Listings of tables and views no longer overlap. 
1.) Enable reflection functions like get_table_names() to work across
schemas. Previously the schema argument was ignored.
2.) Correctly distinguish between views and tables in get_table_names()
and get_view_names().
3.) Support table reflection for View and MaterializedView engines.
Unit tests are updated to show correct behavior.  There is one failing test 
that seems to be unrelated to this PR. (test_insert_truncate)
=> Fixed reflection functions to handle schema and views

clickhouse_sqlalchemy/drivers/http/transport.py
Currently, passing a custom `requests.Session` combined with connection pooling makes all connections share the same custom instance, which allows for more control but may be unexpected.
The change in this PR allows either passing a `requests.Session` instance as until now, or a callable (function, method, class) so that each connection transparently initializes its own separate instance.
=> Support for session factories

clickhouse_sqlalchemy/drivers/http/transport.py
The current default Unicode error handler `escape` does not exist and will cause an error when triggered (`unknown error handler name 'escape'`). This changes it back to `replace` which is what it was before https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/120.
=> Fix default Unicode error handler

clickhouse_sqlalchemy/drivers/http/base.py, clickhouse_sqlalchemy/drivers/http/connector.py, clickhouse_sqlalchemy/drivers/http/transport.py, clickhouse_sqlalchemy/drivers/http/utils.py, tests/drivers/http/test_select.py, tests/util.py
- fixes #168 
It is very disgusting to rewrite sql with 'FORMAT TabSeparatedWithNamesAndTypes' and it may cause some other problems.
Instead, we can add a http params to solve it easily.
see: https://github.com/ClickHouse/ClickHouse/blob/ab9fc572d536ec9b3b7b2ac8628a3824bdeeda4c/src/Server/HTTPHandler.cpp#L734
=> use http params to specify clickhouse data format

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/drivers/compilers/typecompiler.py, clickhouse_sqlalchemy/types/__init__.py, clickhouse_sqlalchemy/types/common.py, tests/test_compiler.py, tests/types/test_boolean.py
- fixes #212
Could not find any relevant doc entries to update.
Note, I changed the ClickHouseDialect configuration `supports_native_boolean` to `True`. This seemed like a reasonable thing to do but I am not sure exactly how that effects things? Similarly, `non_native_boolean_check_constraint` is kept as is but I do not know what this does either.
With these changes I got it to work as I would like and it allows Alembic migrations for tables with Boolean columns.
Checklist:
=> Add native Boolean type (Bool)

clickhouse_sqlalchemy/drivers/base.py
The type converters dictionary had inconsistencies in how types were mapped between each other. One of these meant that the automatic migration of type changes in a column would fail. This fix resolved the issue.
- fixes #215
Checklist:
=> Fix inconsistency in isshema_names type converters

clickhouse_sqlalchemy/drivers/compilers/sqlcompiler.py, tests/sql/test_regexp_match.py
Implements Clickhouse `regexp_match` https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnElement.regexp_match
Checklist:
=> feat: Added support for regexp_match

clickhouse_sqlalchemy/drivers/compilers/sqlcompiler.py, tests/sql/test_ilike.py
- fixes #228
`column.ilike("text")` was compiled like `lower(column) LIKE lower(text)` request instead of `column ILIKE 'text'`. lower() function in Clickhouse works only with ASCII symbols. So, if column and text contained non-ASCII symbols, ilike operation worked not as expected. In this fix compilation of `ilike()` and 'not_ilike()' methods like `column ILIKE 'text'` and `column NOT ILIKE 'text'` is implemented.
Checklist:
- [ x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ x] Add or update relevant docs, in the docs folder and in code.
- [ x] Ensure PR doesn't contain untouched code reformatting: spaces, etc.
- [ x] Run `flake8` and fix issues.
- [ x] Run `pytest` no tests failed. See …
=> added ilike clause compilation

clickhouse_sqlalchemy/alembic/comparators.py, tests/alembic/test_default_schema_comparators.py, testsrequire.py
I'm really sorry ˙◠˙ for my previous PR, but it broke default Alembic schema comparators for ClickHouse.
I did fix, that register default `('schema', 'default')` comparators for `('schema', 'clickhouse')` _registry branch and added small test case that check it.
Checklist:
=> Make respect non clickhouse engines

setup.py
The `greenlet>=2.0.1` requirement is forced on all projects importing this package, but it's actually not imported (except from tests for which it already is listed in `testsrequire.py`).
Checklist:
=> Remove greenlet dependency

clickhouse_sqlalchemy/types/common.py, tests/types/test_enum16.py, tests/types/test_enum8.py
=> Enum8 and Enum16 supported

clickhouse_sqlalchemy/sql/schema.py
Running `alembic revision --autogenerate` with SQLAlchemy 2.0.23 and Alembic 1.12.1 with existing table will miss all columns, resulting in errors like that if you have any engine configuration related to columns:
```
sqlalchemy.exc.ConstraintColumnNotFoundError: Can't create KeysExpressionOrColumn on table 'table': no column named 'column' is present.
```
In my code with `ReplacingMergeTree` engine and `order_by` set, [It crashes here](https://github.com/sqlalchemy/sqlalchemy/blob/82690b1cfc1e76e5deb622a9afefbcf3be299962/lib/sqlalchemy/sql/schema.py#L4297) as the `parent.c` is empty; after tracing the code, it seems that the `Table` is heavily refactored in SQLAlchemy 2.0, and internally it will use `table.c` to access the columns. This PR added  `.c` clones to `_make_from_standard`, …
=> Fix column reflection in SQLAlchemy 2.0

clickhouse_sqlalchemy/alembic/dialect.py
Fix problem with new sqlalchemy for alembic migrations. 
What changed?
- old sqlalchemy function `table.append_column` [link](https://github.com/sqlalchemy/sqlalchemy/blob/5e88e6e89a2cf5b583670fa5d0b41881f895a711/lib/sqlalchemy/sql/schema.py#L1057)
- new sqlalchemy function `table.append_column` [link](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/sql/schema.py#L1213) 
> replace_existing: When ``True``, allows replacing existing
columns. When ``False``, the default, an warning will be raised
if a column with the same ``.key`` already exists. **A future
version of sqlalchemy will instead rise a warning.**
Checklist:
=> Fixed adding a duplicate column to the alembic table

clickhouse_sqlalchemy/drivers/compilers/sqlcompiler.py, tests/sql/test_regexp_match.py
MATCH raises an error `Unknown function MATCH. Maybe you meant: ['match','path']`
https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions#match
Checklist:
=> fix visit_regexp_match_op_binary to use the correct function name

.github/workflows/sa-versions.yml, clickhouse_sqlalchemy/drivers/native/base.py, setup.py, tests/drivers/native/test_base.py, testsrequire.py
Hello, 
Currently, tests are broken on master because of an update of sqlalchemy. This fix corrects the failing test. 
Note that in the test, I remove the space of the password because it now fails (on purpose) because it is not RFC-1738 compliment.
For context, see 
- https://github.com/sqlalchemy/sqlalchemy/pull/10726
- https://github.com/sqlalchemy/sqlalchemy/issues/10662
- https://github.com/sqlalchemy/sqlalchemy/commit/4438883c9703affa3f441be9a230a5f751905a05
Checklist:
=> fix(parsing): change the way to quote db_url to fix the test broken by sqlalchemy 2.0.25

clickhouse_sqlalchemy/drivers/compilers/sqlcompiler.py, tests/sql/test_selectable.py
=> Add support for SELECT ON

clickhouse_sqlalchemy/sql/selectable.py, tests/sql/test_selectable.py
We discover than requests like `select(table1).join(table2, table2.id == table1.table2Id).where([...])`
didn't work with clickhouse-sqlalchemy but did work with standard sqlalchemy because `select(table1).join(table2, table2.id == table1.table2Id)` is a `Select` object in sqlalchemy2.
This PR fix this (just changed the return of the `join` method) and add a test to prove the fix works.
The diff in the test is massive because I added a for loop to test both ways to compute the join statement. Let me know if you think there is a better way to write the test
Checklist:
=> fix: fix select.join

clickhouse_sqlalchemy/drivers/compilers/sqlcompiler.py, clickhouse_sqlalchemy/sql/functions.py, docs/features.rst, tests/sql/test_functions.py
=> Add support for quantile and quantileIf functions

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/drivers/compilers/typecompiler.py, clickhouse_sqlalchemy/drivers/util.py, clickhouse_sqlalchemy/types/__init__.py, clickhouse_sqlalchemy/types/common.py, docs/features.rst, tests/drivers/test_util.py, tests/test_ddl.py, tests/test_reflection.py
=> Add aggregate types

clickhouse_sqlalchemy/drivers/base.py, tests/sql/test_selectable.py
=> Support Nested Map Type (#314)

clickhouse_sqlalchemy/drivers/base.py, clickhouse_sqlalchemy/drivers/compilers/typecompiler.py, clickhouse_sqlalchemy/types/__init__.py, clickhouse_sqlalchemy/types/common.py, tests/types/test_json.py
=> feat: Add JSON type

tests/types/test_json.py
https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/317
Checklist:
=> fix: fixed required_server_version to v22.6.1 on json type

clickhouse_sqlalchemy/drivers/http/escaper.py, tests/drivers/http/test_escaping.py
The `Escaper.escape` method curently doesn't support `uuid.UUID` but it probably should since the other protocols support sending uuid. This pr adds uuid to the escaper case.
Checklist:
=> feat: support uuid for http protocol

clickhouse_sqlalchemy/drivers/asynch/base.py, tests/drivers/asynch/test_cursor.py
=> Support for asynchronous streaming results

.github/workflows/actions.yml, .github/workflows/docs.yml, .github/workflows/sa-versions.yml
=> ci: update github action to use services
